# Generated by Django 5.1 on 2024-08-13 06:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_name', models.CharField(max_length=100)),
                ('com_logo', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('com_address', models.CharField(max_length=100)),
                ('com_phone', models.IntegerField(max_length=10)),
                ('com_email', models.EmailField(max_length=100)),
                ('com_website', models.URLField(max_length=100)),
                ('com_description', ckeditor.fields.RichTextField()),
                ('com_facebook', models.URLField(max_length=100)),
                ('com_twitter', models.URLField(max_length=100)),
                ('com_linked_in', models.URLField(max_length=100)),
                ('com_instagram', models.URLField(max_length=100)),
                ('com_youtube', models.URLField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
