# Generated by Django 5.0.6 on 2024-08-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_company_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='more_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.AlterField(
            model_name='company_details',
            name='com_phone',
            field=models.IntegerField(),
        ),
    ]
