# Generated by Django 5.0.6 on 2024-08-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_more_items_alter_company_details_com_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_name', models.CharField(max_length=100)),
                ('com_logo', models.ImageField(upload_to='photos/%Y/%m/%d')),
            ],
            options={
                'verbose_name_plural': 'Banners',
            },
        ),
    ]
