# Generated by Django 5.0.6 on 2024-08-17 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='banner',
        ),
    ]
