# Generated by Django 5.0.6 on 2024-08-17 18:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_delete_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d')),
            ],
            options={
                'verbose_name_plural': 'Banners',
            },
        ),
    ]
