# Generated by Django 5.0.6 on 2024-08-18 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_category_1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category_1',
        ),
    ]
