# Generated by Django 5.0.6 on 2024-08-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_delete_category_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d')),
            ],
            options={
                'verbose_name_plural': 'Category-1',
            },
        ),
    ]
