# Generated by Django 5.0.6 on 2024-08-25 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_products_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category_1',
        ),
    ]
